[package]
name = "robocup-base-station"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.5.4"
embedded-hal = "0.2.7"
ncomm = { version = "0.4.1", features = ["packed-struct"] }
packed_struct = "0.10.1"
sx127 = { git = "https://github.com/N8BWert/sx127" }

[dependencies.robojackets-robocup-rtp]
version = "0.1.7"
default_features = false
features = ["std"]

[dependencies.rppal]
version = "0.14.1"
features = ["hal"]

[dependencies.clap]
version = "4.4.4"
features = ["derive"]

[features]
default = ["benchmark"]
benchmark = []